services:
  cex-mng-colas-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV:-production}
    image: cex-mng-colas-app:latest
    container_name: cex-mng-colas-app
    ports:
      - "5000:80"
    networks:
      - cex-network

networks:
  cex-network:
    external: true
