services:
  construction-db-ui-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV:-production}
    image: construction-db-ui-app:latest
    container_name: construction-db-ui-app
    ports:
      - "5000:80"
    networks:
      - construction-network

networks:
  construction-network:
    external: true
